# Generated by Django 2.1.3 on 2018-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20181124_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatoroption',
            name='option',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='indicatoroption',
            unique_together={('company', 'option')},
        ),
    ]
