# Generated by Django 2.1.3 on 2018-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicaotrImage',
            field=models.ImageField(default='', upload_to='', verbose_name='Indicator Image'),
        ),
    ]
