# Generated by Django 2.1.3 on 2018-11-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_indicator_indicaotrimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.FileField(upload_to='', verbose_name='Image path')),
                ('path', models.FilePathField()),
                ('active', models.BooleanField(default=True, verbose_name='Indicators Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
            ],
            options={
                'ordering': ('id',),
            },
        ),

        migrations.AddField(
            model_name='indicator',
            name='images',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicatorImage', to='API.Image', verbose_name='Indicator Images'),
        ),
    ]
