# Generated by Django 2.1.3 on 2018-11-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20181115_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='imagePath',
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FilePathField(path='C:/Users\\kevin\\Google Drive\\Work\\INCAMedical\\Web'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='images',
            field=models.ForeignKey(blank=True,  on_delete=django.db.models.deletion.CASCADE, related_name='indicatorImage', to='API.Image', verbose_name='Indicator Images'),
        ),
    ]
