# Generated by Django 2.1.3 on 2018-11-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20181115_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='indicaotrImage',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='images',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicatorImage', to='API.Image', verbose_name='Indicator Images'),
        ),
    ]
