# Generated by Django 2.1.3 on 2018-11-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20181115_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateindicator',
            name='images',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templateIndicatorImage', to='API.Image', verbose_name='Template Indicator Images'),
        ),
    ]
