# Generated by Django 2.1.3 on 2018-11-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_templateindicator_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='images',
        ),
    ]
