# Generated by Django 2.1.3 on 2018-11-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_templateindicator_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateindicator',
            name='images',
            field=models.ManyToManyField(to='API.Image'),
        ),
    ]
